### ISSUE TITLE
只有一条数据的时候，怎么移除轮播

### ISSUE THREAD

**Issue by zebraoo** [iYouthy/banner-view#1]
只有一条数据的时候，还可以手动切换或自动轮播，怎么取消？

**Comment by youthyJJ** [comment]
有一个`autoSwipe`的变量，设置为`false`即可手动停止自动轮播。
在你的场景中，你应该监听真实数据的Flow，判断真实数据的数量，如果数据数量小于等于1，则将`autoSwipe`置为`false`，否则置为`true`。

**Comment by zebraoo** [comment]
> 有一个`autoSwipe`的变量，设置为`false`即可手动停止自动轮播。 在你的场景中，你应该监听真实数据的Flow，判断真实数据的数量，如果数据数量小于等于1，则将`autoSwipe`置为`false`，否则置为`true`。

无效
在souce中设置如下可行
override suspend fun load(params: LoadParams<Int>): LoadResult<Int, BannerData> =
        when(bannerDataList.isEmpty()){
            true -> LoadResult.Error(PagingSourceEmptyException())
            false-> {
                if (bannerDataList.size<=1){
                    LoadResult.Page(bannerDataList,  null , null)
                }else{
                    val key = params.key ?: 0
                    LoadResult.Page(bannerDataList,  key-1 , key+1)
                }

            }
        }

**Comment by iYouthy** [comment]
我试了我说的是可以的:
1. 在`BannerVm`中为下游提供一个真实数据的flow:
    ```Kotlin
    val realList get() = repo.bannerListFlow
    ```

2. 在控制器(Fragment)中, 监听`realList`, 并判断数据数量:
    ```Kotlin
    launch {
        repeatOnLifecycle(Lifecycle.State.RESUMED) {
            bannerVm.realList.collect {
                binding.vBanner.autoSwipe = (it.size > 1)
            }
        }
    }
    ```

如果你需要禁止用户手动滑动, 则需要为`BannerView`暴露出`ViewPager2`的`isUserInputEnabled`接口:
    ```Kotlin
     var isUserInputEnabled
        get() = binding.vpBanner.isUserInputEnabled
        set(value) {
            binding.vpBanner.isUserInputEnabled = value
        }
    ```
